#include <stdlib.h>

int main(void) {
    int* xnxnxu = malloc(1);
    int* suliad = malloc(1);
    int* scguvh = malloc(1);
    int* vjuabd = malloc(1);
    int* snzhyz = malloc(1);
    int* qvlswn = malloc(1);
    int* hpwraw = malloc(1);
    int* zvqqbd = malloc(1);
    int* qwaybq = malloc(1);
    int* yeuwzb = malloc(1);
    int* wuokeo = malloc(1);
    int* yinujw = malloc(1);
    int* gsvhva = malloc(1);
    int* tbktxd = malloc(1);
    int* htczyh = malloc(1);
    int* lxjmmo = malloc(1);
    int* nqxrhy = malloc(1);
    int* fibdot = malloc(1);
    int* pjdpwe = malloc(1);
    int* fohodn = malloc(1);
    int* rgtjkp = malloc(1);
    int* sytygx = malloc(1);
    int* khadub = malloc(1);
    int* pvfuyk = malloc(1);
    int* ngjkkg = malloc(1);
    int* himkdu = malloc(1);
    int* lmgmzc = malloc(1);
    int* qbgsyy = malloc(1);
    int* xpucnb = malloc(1);
    int* dxvncl = malloc(1);
    int* xqhvxc = malloc(1);
    int* wtjjhj = malloc(1);
    int* pzbbsq = malloc(1);
    int* gngywy = malloc(1);
    int* xljnxj = malloc(1);
    int* byjjnh = malloc(1);
    int* uwkudr = malloc(1);
    int* oeslyr = malloc(1);
    int* bnjljd = malloc(1);
    int* xwkokt = malloc(1);
    int* zybukf = malloc(1);
    int* uefgnq = malloc(1);
    int* sctikz = malloc(1);
    int* osequr = malloc(1);
    int* mgoutw = malloc(1);
    int* urmbzz = malloc(1);
    int* javxml = malloc(1);
    int* coulcq = malloc(1);
    int* vdqcgf = malloc(1);
    int* ozgtqk = malloc(1);
    int* uwwrcg = malloc(1);
    int* ezdlbr = malloc(1);
    int* hqllub = malloc(1);
    int* iwojuc = malloc(1);
    int* wvmgwx = malloc(1);
    int* djbwnz = malloc(1);
    int* pquiwj = malloc(1);
    int* yymfkm = malloc(1);
    int* migkxb = malloc(1);
    int* jrdwog = malloc(1);
    int* fzpdtq = malloc(1);
    int* epdqda = malloc(1);
    int* bldsdh = malloc(1);
    int* qidots = malloc(1);
    int* svbxjc = malloc(1);
    int* rwsdkq = malloc(1);
    int* qfzvsk = malloc(1);
    int* ilbhak = malloc(1);
    int* jrwmau = malloc(1);
    int* qhlhaw = malloc(1);
    int* fyeynr = malloc(1);
    int* kqnidb = malloc(1);
    int* zygnva = malloc(1);
    int* arxazp = malloc(1);
    int* atihcu = malloc(1);
    int* ojloog = malloc(1);
    int* pvipiq = malloc(1);
    int* gzpolm = malloc(1);
    int* oimwkl = malloc(1);
    int* kyxvse = malloc(1);
    int* jsmnry = malloc(1);
    int* wfghks = malloc(1);
    int* ozowqz = malloc(1);
    int* buwpux = malloc(1);
    int* txzuwq = malloc(1);
    int* jnsqcu = malloc(1);
    int* etxrjy = malloc(1);
    int* sbxlxt = malloc(1);
    int* spsrnf = malloc(1);
    int* yywrbi = malloc(1);
    int* bzzagz = malloc(1);
    int* xlgooz = malloc(1);
    int* qndimx = malloc(1);
    int* hrviyg = malloc(1);
    int* yibiri = malloc(1);
    int* ntsgti = malloc(1);
    int* tssuod = malloc(1);
    int* pwbylh = malloc(1);
    int* zepycl = malloc(1);
    int* qcqtek = malloc(1);
    int* jttnlx = malloc(1);
    int* jzkwwr = malloc(1);
    int* skihxu = malloc(1);
    int* bmhube = malloc(1);
    int* zgdxsc = malloc(1);
    int* kohsds = malloc(1);
    int* myxqlt = malloc(1);
    int* mjlqal = malloc(1);
    int* pdukyf = malloc(1);
    int* kqbdkh = malloc(1);
    int* hdnfpo = malloc(1);
    int* mdwxya = malloc(1);
    int* jqbfvs = malloc(1);
    int* uhdhgr = malloc(1);
    int* deqwew = malloc(1);
    int* ogatpl = malloc(1);
    int* ndawce = malloc(1);
    int* pagtfp = malloc(1);
    int* eispfq = malloc(1);
    int* sdczmc = malloc(1);
    int* rqdkkm = malloc(1);
    int* ylsujw = malloc(1);
    int* cuetah = malloc(1);
    int* jykpqh = malloc(1);
    int* blmlys = malloc(1);
    int* bwsgit = malloc(1);
    int* gkhjqd = malloc(1);
    int* ktomha = malloc(1);
    int* fngkyx = malloc(1);
    int* egrnke = malloc(1);
    int* zxdduw = malloc(1);
    int* uraxwk = malloc(1);
    int* doidaz = malloc(1);
    int* roiqmj = malloc(1);
    int* amroxz = malloc(1);
    int* nfnmoh = malloc(1);
    int* syeooe = malloc(1);
    int* mtpkby = malloc(1);
    int* oikdsl = malloc(1);
    int* rtkvlu = malloc(1);
    int* edgbkq = malloc(1);
    int* rawcfo = malloc(1);
    int* uhcsng = malloc(1);
    int* jflsxx = malloc(1);
    int* dyzhgg = malloc(1);
    int* fcqgil = malloc(1);
    int* aavjjp = malloc(1);
    int* utpffs = malloc(1);
    int* xkhbmc = malloc(1);
    int* wajimx = malloc(1);
    int* qrtvqx = malloc(1);
    int* nbmzty = malloc(1);
    int* jlkbel = malloc(1);
    int* tbfgfu = malloc(1);
    int* qfeshf = malloc(1);
    int* donqkb = malloc(1);
    int* xnsirv = malloc(1);
    int* blbzou = malloc(1);
    int* vjwhxk = malloc(1);
    int* vxnnkb = malloc(1);
    int* eoxpgt = malloc(1);
    int* vsmxrm = malloc(1);
    int* lglstf = malloc(1);
    int* gujlmz = malloc(1);
    int* bqhblw = malloc(1);
    int* mfxblc = malloc(1);
    int* toxyxs = malloc(1);
    int* aqsypg = malloc(1);
    int* tesznz = malloc(1);
    int* stfvkl = malloc(1);
    int* zdluts = malloc(1);
    int* ynagog = malloc(1);
    int* axoqkv = malloc(1);
    int* slsmsv = malloc(1);
    int* ustcdx = malloc(1);
    int* wthuha = malloc(1);
    int* gzgjvc = malloc(1);
    int* jjpqvi = malloc(1);
    int* vhiezl = malloc(1);
    int* ypzqvu = malloc(1);
    int* dppenz = malloc(1);
    int* qkjizr = malloc(1);
    int* ckuybr = malloc(1);
    int* zkotff = malloc(1);
    int* mchoic = malloc(1);
    int* atshcg = malloc(1);
    int* myzgmt = malloc(1);
    int* pdqoon = malloc(1);
    int* wrqypt = malloc(1);
    int* oesudz = malloc(1);
    int* yzjoon = malloc(1);
    int* cnycxf = malloc(1);
    int* igimhs = malloc(1);
    int* puonjo = malloc(1);
    int* jhyput = malloc(1);
    int* opbqxy = malloc(1);
    int* vgfnse = malloc(1);
    int* fwxlkm = malloc(1);
    int* shcjbi = malloc(1);
    int* bkjeon = malloc(1);
    int* nermij = malloc(1);
    int* hjhzgb = malloc(1);
    int* wvohkk = malloc(1);
    int* braabi = malloc(1);
    int* qgkagi = malloc(1);
    int* pyfvrb = malloc(1);
    int* ysjetz = malloc(1);
    int* igxpak = malloc(1);
    int* wwjljl = malloc(1);
    int* fwigqc = malloc(1);
    int* rfbpmx = malloc(1);
    int* byzurl = malloc(1);
    int* hreqhk = malloc(1);
    int* bwlwdc = malloc(1);
    int* wprycl = malloc(1);
    int* nisghw = malloc(1);
    int* cdskww = malloc(1);
    int* udcoti = malloc(1);
    int* ueibwd = malloc(1);
    int* ndcwhv = malloc(1);
    int* qkxzdb = malloc(1);
    int* tdrgiu = malloc(1);
    int* xoalnn = malloc(1);
    int* hwtceo = malloc(1);
    int* hpdvvw = malloc(1);
    int* nfpcip = malloc(1);
    int* sqzori = malloc(1);
    int* jdmgow = malloc(1);
    int* afjmvg = malloc(1);
    int* kcoegj = malloc(1);
    int* anhsgw = malloc(1);
    int* mfjnxp = malloc(1);
    int* wwnqfr = malloc(1);
    int* dhjbiz = malloc(1);
    int* iiqshk = malloc(1);
    int* bsusyk = malloc(1);
    int* omrqhc = malloc(1);
    int* iihunc = malloc(1);
    int* ifabwt = malloc(1);
    int* topnco = malloc(1);
    int* pxdwmp = malloc(1);
    int* gsgiel = malloc(1);
    int* mykebk = malloc(1);
    int* klgdba = malloc(1);
    int* vwmgrs = malloc(1);
    int* vqxxwt = malloc(1);
    int* kgbmcx = malloc(1);
    int* rdnlky = malloc(1);
    int* vegfzb = malloc(1);
    int* upmhww = malloc(1);

    free(hreqhk);
    free(rqdkkm);
    free(fohodn);
    free(jrwmau);
    free(pagtfp);
    free(bwlwdc);
    free(fyeynr);
    free(ojloog);
    free(jlkbel);
    free(anhsgw);
    free(eoxpgt);
    free(coulcq);
    free(qkjizr);
    free(xpucnb);
    free(pdqoon);
    free(wvohkk);
    free(wrqypt);
    free(wfghks);
    free(zygnva);
    free(pwbylh);
    free(yzjoon);
    free(vhiezl);
    free(dhjbiz);
    free(ndawce);
    free(syeooe);
    free(ckuybr);
    free(wtjjhj);
    free(uwkudr);
    free(tbktxd);
    free(jrdwog);
    free(zkotff);
    free(dxvncl);
    free(igimhs);
    free(jnsqcu);
    free(jqbfvs);
    free(jykpqh);
    free(aavjjp);
    free(etxrjy);
    free(pzbbsq);
    free(iihunc);
    free(xnsirv);
    free(uwwrcg);
    free(egrnke);
    free(stfvkl);
    free(oimwkl);
    free(rgtjkp);
    free(rdnlky);
    free(roiqmj);
    free(blmlys);
    free(wthuha);
    free(snzhyz);
    free(hqllub);
    free(ypzqvu);
    free(gkhjqd);
    free(suliad);
    free(nqxrhy);
    free(myzgmt);
    free(zgdxsc);
    free(lglstf);
    free(deqwew);
    free(txzuwq);
    free(qgkagi);
    free(yymfkm);
    free(ifabwt);
    free(zdluts);
    free(xlgooz);
    free(bzzagz);
    free(qwaybq);
    free(vqxxwt);
    free(eispfq);
    free(zepycl);
    free(jzkwwr);
    free(wwjljl);
    free(jjpqvi);
    free(osequr);
    free(amroxz);
    free(fwxlkm);
    free(jdmgow);
    free(xnxnxu);
    free(opbqxy);
    free(hpdvvw);
    free(urmbzz);
    free(fcqgil);
    free(yibiri);
    free(qndimx);
    free(qfzvsk);
    free(nfnmoh);
    free(zxdduw);
    free(vjuabd);
    free(bkjeon);
    free(spsrnf);
    free(mgoutw);
    free(vegfzb);
    free(rtkvlu);
    free(rfbpmx);
    free(upmhww);
    free(gsvhva);
    free(kcoegj);
    free(ezdlbr);
    free(wvmgwx);
    free(afjmvg);
    free(cuetah);
    free(mdwxya);
    free(svbxjc);
    free(kqnidb);
    free(dyzhgg);
    free(ynagog);
    free(zybukf);
    free(tbfgfu);
    free(gngywy);
    free(byzurl);
    free(jhyput);
    free(omrqhc);
    free(pdukyf);
    free(iwojuc);
    free(sbxlxt);
    free(uraxwk);
    free(xoalnn);
    free(mtpkby);
    free(ntsgti);
    free(nbmzty);
    free(scguvh);
    free(bwsgit);
    free(pxdwmp);
    free(qrtvqx);
    free(igxpak);
    free(ngjkkg);
    free(xqhvxc);
    free(byjjnh);
    free(bmhube);
    free(wprycl);
    free(edgbkq);
    free(ozowqz);
    free(tdrgiu);
    free(cdskww);
    free(fzpdtq);
    free(ndcwhv);
    free(uefgnq);
    free(dppenz);
    free(axoqkv);
    free(doidaz);
    free(udcoti);
    free(sqzori);
    free(gujlmz);
    free(mfxblc);
    free(slsmsv);
    free(ylsujw);
    free(lmgmzc);
    free(xwkokt);
    free(yeuwzb);
    free(qfeshf);
    free(donqkb);
    free(kyxvse);
    free(ozgtqk);
    free(uhdhgr);
    free(tesznz);
    free(bqhblw);
    free(mykebk);
    free(shcjbi);
    free(buwpux);
    free(nisghw);
    free(xljnxj);
    free(ilbhak);
    free(qkxzdb);
    free(sctikz);
    free(sytygx);
    free(kqbdkh);
    free(wwnqfr);
    free(qidots);
    free(htczyh);
    free(qhlhaw);
    free(ogatpl);
    free(fwigqc);
    free(bsusyk);
    free(ktomha);
    free(lxjmmo);
    free(toxyxs);
    free(vjwhxk);
    free(klgdba);
    free(hpwraw);
    free(himkdu);
    free(sdczmc);
    free(hrviyg);
    free(jttnlx);
    free(pvfuyk);
    free(atshcg);
    free(hwtceo);
    free(rawcfo);
    free(aqsypg);
    free(ueibwd);
    free(uhcsng);
    free(gsgiel);
    free(wuokeo);
    free(migkxb);
    free(mjlqal);
    free(puonjo);
    free(zvqqbd);
    free(javxml);
    free(pjdpwe);
    free(skihxu);
    free(pquiwj);
    free(vsmxrm);
    free(rwsdkq);
    free(epdqda);
    free(djbwnz);
    free(gzgjvc);
    free(kgbmcx);
    free(ustcdx);
    free(mfjnxp);
    free(oikdsl);
    free(hjhzgb);
    free(jsmnry);
    free(utpffs);
    free(yinujw);
    free(blbzou);
    free(oesudz);
    free(nfpcip);
    free(bldsdh);
    free(bnjljd);
    free(topnco);
    free(iiqshk);
    free(fibdot);
    free(ysjetz);
    free(khadub);
    free(vgfnse);
    free(braabi);
    free(vxnnkb);
    free(vwmgrs);
    free(pvipiq);
    free(gzpolm);
    free(myxqlt);
    free(atihcu);
    free(mchoic);
    free(qvlswn);
    free(cnycxf);
    free(fngkyx);
    free(kohsds);
    free(qbgsyy);
    free(yywrbi);
    free(xkhbmc);
    free(vdqcgf);
    free(nermij);
    free(qcqtek);
    free(jflsxx);
    free(arxazp);

    return 0;
}